using OfficeOpenXml;
using System.IO;

namespace Mixogo.ClassesLibraries.Helpers
{
    public class XLSReportHelper
    {
        ExcelPackage excelPackage;
        ExcelWorksheet wsSheet1;

        public XLSReportHelper()
        {

        }

        public void ConfigureDocument()
        {
            excelPackage = new ExcelPackage();
            wsSheet1 = excelPackage.Workbook.Worksheets.Add(BaseConstants.SHEET1_DEFAULT_NAME);

            using (var rng = wsSheet1.Cells[2,2,2,2])
            {
                rng.Value = "Welcome to this tutorial";
                rng.Merge = true;
                rng.Style.Font.Size = 16;
                rng.Style.Font.Bold = true;
                rng.Style.Font.Italic = true;
            }

            wsSheet1.Protection.IsProtected = false;
            wsSheet1.Protection.AllowSelectLockedCells = false;
            excelPackage.SaveAs(new FileInfo(@"C:\Users\CBQA-0090\autogenerated\new_file.xlsx"));

        }
    }
}
